python generate_fedtask.py \
    --benchmark food101_8_classes_fixed \
    --dist 1 \
    --skew 0.1 \
    --num_clients 20 \
    --seed 0 \
    --missing \
    --missing_ratio_train 0.7 \
    --missing_ratio_test 0.7 \
    --missing_type_train text \
    --missing_type_test text \
    --both_ratio 0 \
    --max_text_len 40
python main.py \
    --task food101_8_classes_fixed_cnum20_dist1_skew0.1_seed0_missing_ratio_0.7_0.7_missing_type_text_text_both_ratio_0.0 \
    --model proposal_fedprox \
    --algorithm multimodal.food101_8_classes_fixed.proposal_fedprox \
    --sample full \
    --aggregate other \
    --num_rounds 250 \
    --proportion 1.0 \
    --lr_scheduler 0 \
    --seed 5678 \
    --fedprox_lambda 0.01 \
    --learning_rate 0.05 \
    --reduce_sim_scalar 0.005 \
    --num_epochs 1 \
    --num_outer_loops 5 \
    --learning_rate_decay 1.0 \
    --note rebuttal \
    --batch_size 128 \
    --test_batch_size 128 \
    --max_text_len 40 \
    --gpu 0 
    \
    --wandb
python generate_fedtask.py \
    --benchmark food101_8_classes_fixed \
    --dist 1 \
    --skew 0.1 \
    --num_clients 20 \
    --seed 0 \
    --missing \
    --missing_ratio_train 0.7 \
    --missing_ratio_test 0.7 \
    --missing_type_train image \
    --missing_type_test image \
    --both_ratio 0 \
    --max_text_len 40
python main.py \
    --task food101_8_classes_fixed_cnum20_dist1_skew0.1_seed0_missing_ratio_0.7_0.7_missing_type_image_image_both_ratio_0.0 \
    --model proposal_fedprox \
    --algorithm multimodal.food101_8_classes_fixed.proposal_fedprox \
    --sample full \
    --aggregate other \
    --num_rounds 250 \
    --proportion 1.0 \
    --lr_scheduler 0 \
    --seed 5678 \
    --fedprox_lambda 0.01 \
    --learning_rate 0.05 \
    --reduce_sim_scalar 0.005 \
    --num_epochs 1 \
    --num_outer_loops 5 \
    --learning_rate_decay 1.0 \
    --note rebuttal \
    --batch_size 128 \
    --test_batch_size 128 \
    --max_text_len 40 \
    --gpu 0 \
    --wandb
python generate_fedtask.py \
    --benchmark food101_8_classes_fixed \
    --dist 1 \
    --skew 0.1 \
    --num_clients 20 \
    --seed 0 \
    --missing \
    --missing_ratio_train 0.7 \
    --missing_ratio_test 0.7 \
    --missing_type_train both \
    --missing_type_test both \
    --both_ratio 0.5 \
    --max_text_len 40
python main.py \
    --task food101_classification_8_classes_cnum20_dist1_skew0.1_seed0_missing_ratio_0.7_0.7_missing_type_both_both_both_ratio_0.5 \
    --model proposal_fedprox \
    --algorithm multimodal.food101_8_classes_fixed.proposal_fedprox \
    --sample full \
    --aggregate other \
    --num_rounds 250 \
    --proportion 1.0 \
    --lr_scheduler 0 \
    --seed 5678 \
    --fedprox_lambda 0.01 \
    --learning_rate 0.05 \
    --reduce_sim_scalar 0.005 \
    --num_epochs 1 \
    --num_outer_loops 5 \
    --learning_rate_decay 1.0 \
    --note rebuttal \
    --batch_size 128 \
    --test_batch_size 128 \
    --max_text_len 40 \
    --gpu 0 \
    --wandb